#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Create a local Azure deployment env file with stable generated resource names.

Usage:
  scripts/azure/init-env.sh [--output PATH] [--force] [--print]

Options:
  --output PATH  Env file to write. Default: scripts/azure/env.local.
  --force        Replace an existing output file.
  --print        Print the output path after writing.
  -h, --help     Show this help text.

Notes:
  - The generated file contains no secrets.
  - The generated ACR and storage names use an eight-digit random suffix.
  - scripts/azure/env.local is ignored by git via the repo's *.local rule.
EOF
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/common.sh"

OUTPUT_PATH="${SCRIPT_DIR}/env.local"
FORCE="0"
PRINT_PATH="0"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output)
      [[ $# -ge 2 ]] || fail "--output requires a value."
      OUTPUT_PATH="$2"
      shift 2
      ;;
    --force)
      FORCE="1"
      shift
      ;;
    --print)
      PRINT_PATH="1"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      fail "Unknown argument: $1"
      ;;
  esac
done

if [[ -e "$OUTPUT_PATH" && "$FORCE" != "1" ]]; then
  fail "${OUTPUT_PATH} already exists. Use --force to replace it."
fi

UNIQUE_SUFFIX="$(random_numeric_suffix)"
ACR_NAME="acremailcleaner${UNIQUE_SUFFIX}"
STORAGE_ACCOUNT="stemcleaner${UNIQUE_SUFFIX}"

[[ "$UNIQUE_SUFFIX" =~ ^[0-9]{8}$ ]] || fail "Generated suffix was not eight digits."
[[ ${#ACR_NAME} -le 50 ]] || fail "Generated ACR name is too long: ${ACR_NAME}"
[[ ${#STORAGE_ACCOUNT} -le 24 ]] || fail "Generated storage account name is too long: ${STORAGE_ACCOUNT}"

mkdir -p "$(dirname "$OUTPUT_PATH")"
tmp_file="$(mktemp)"
cat >"$tmp_file" <<EOF
# Generated by scripts/azure/init-env.sh.
# This file contains nonsecret Azure deployment settings only.

export AZURE_LOCATION="centralus"
export AZURE_RESOURCE_GROUP="rg-emailcleaner-prod"
export AZURE_CONTAINERAPPS_ENV="cae-emailcleaner-prod"
export AZURE_JOB_NAME="caj-emailcleaner-prod"
export AZURE_LOG_WORKSPACE="law-emailcleaner-prod"
export AZURE_FILE_SHARE="emailcleaner-data"
export AZURE_STORAGE_MOUNT_NAME="emailcleaner-data"
export AZURE_IMAGE_NAME="emailcleaner"
export AZURE_ACR_RESOURCE_GROUP="rg-emailcleaner-prod"
export AZURE_CREATE_ACR="true"
export AZURE_SCAN_CRON="*/15 * * * *"
export AZURE_ACR_SKU="Basic"
export AZURE_JOB_TRIGGER_TYPE="Manual"
export AZURE_CPU="0.25"
export AZURE_MEMORY="0.5Gi"
export AZURE_BOOTSTRAP_IMAGE="mcr.microsoft.com/azuredocs/containerapps-helloworld:latest"
export AZURE_MAX_RUNTIME_SECONDS="3600"
export AZURE_REPLICA_TIMEOUT="3600"
export AZURE_REPLICA_RETRY_LIMIT="0"
export AZURE_PARALLELISM="1"
export AZURE_REPLICA_COMPLETION_COUNT="1"
export AZURE_UNIQUE_SUFFIX="${UNIQUE_SUFFIX}"
export AZURE_ACR_NAME="${ACR_NAME}"
export AZURE_STORAGE_ACCOUNT="${STORAGE_ACCOUNT}"
export AZURE_SECRET_ENV_VARS="OPENAI_API_KEY EMAIL_CLEANER_GMAIL_EMAIL_1 EMAIL_CLEANER_GMAIL_APP_PASSWORD_1 EMAIL_CLEANER_YAHOO_EMAIL_1 EMAIL_CLEANER_YAHOO_APP_PASSWORD_1"
EOF
mv "$tmp_file" "$OUTPUT_PATH"
chmod 600 "$OUTPUT_PATH"

info "Wrote ${OUTPUT_PATH}."
if [[ "$PRINT_PATH" == "1" ]]; then
  printf '%s\n' "$OUTPUT_PATH"
fi
