#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Create a local shared Azure Container Registry env file.

Usage:
  scripts/azure/init-shared-acr-env.sh [--output PATH] [--force] [--print]

Options:
  --output PATH  Env file to write. Default: scripts/azure/shared-acr.local.
  --force        Replace an existing output file.
  --print        Print the output path after writing.
  -h, --help     Show this help text.
EOF
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/common.sh"

OUTPUT_PATH="${SCRIPT_DIR}/shared-acr.local"
FORCE="0"
PRINT_PATH="0"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output)
      [[ $# -ge 2 ]] || fail "--output requires a value."
      OUTPUT_PATH="$2"
      shift 2
      ;;
    --force)
      FORCE="1"
      shift
      ;;
    --print)
      PRINT_PATH="1"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      fail "Unknown argument: $1"
      ;;
  esac
done

if [[ -e "$OUTPUT_PATH" && "$FORCE" != "1" ]]; then
  fail "${OUTPUT_PATH} already exists. Use --force to replace it."
fi

UNIQUE_SUFFIX="$(random_numeric_suffix)"
ACR_NAME="acrautomationjobs${UNIQUE_SUFFIX}"
[[ ${#ACR_NAME} -le 50 ]] || fail "Generated ACR name is too long: ${ACR_NAME}"

mkdir -p "$(dirname "$OUTPUT_PATH")"
tmp_file="$(mktemp)"
cat >"$tmp_file" <<EOF
# Generated by scripts/azure/init-shared-acr-env.sh.
# This file contains nonsecret shared Azure Container Registry settings only.

export AZURE_LOCATION="centralus"
export AZURE_ACR_RESOURCE_GROUP="rg-shared-container-registry-prod"
export AZURE_ACR_NAME="${ACR_NAME}"
export AZURE_ACR_SKU="Basic"
EOF
mv "$tmp_file" "$OUTPUT_PATH"
chmod 600 "$OUTPUT_PATH"

info "Wrote ${OUTPUT_PATH}."
if [[ "$PRINT_PATH" == "1" ]]; then
  printf '%s\n' "$OUTPUT_PATH"
fi
